var R=require("./chunks/[turbopack]_runtime.js")("server/instrumentation.js")
R.c("server/chunks/[root-of-the-server]__1zl6_d4._.js")
R.c("server/chunks/node_modules_@sentry_conventions_dist_0mfx7rv._.js")
R.c("server/chunks/node_modules_@sentry_core_build_cjs_1_yel3m._.js")
R.c("server/chunks/node_modules_@sentry_node-core_build_cjs_1nceneq._.js")
R.c("server/chunks/node_modules_@sentry_node_build_cjs_10tmr5f._.js")
R.c("server/chunks/node_modules_@sentry_server-utils_build_cjs_0j1vn-_._.js")
R.c("server/chunks/node_modules_meriyah_dist_meriyah_cjs_1489o-8._.js")
R.c("server/chunks/node_modules_@sentry_nextjs_build_cjs_2164cb0._.js")
R.c("server/chunks/[root-of-the-server]__1bbt6l3._.js")
R.c("server/chunks/[root-of-the-server]__0mn049n._.js")
R.m("[project]/apps/web/instrumentation.ts [instrumentation] (ecmascript)")
module.exports=R.m("[project]/apps/web/instrumentation.ts [instrumentation] (ecmascript)").exports
