import js from "@eslint/js";
import tseslint from "typescript-eslint";

/**
 * Flat config for the whole monorepo.
 *
 * The rule that earns this file's existence is the `no-restricted-imports`
 * block below. Plan D2 rates cross-tenant leakage as the one Critical risk
 * with no recovery, and the service-role client is the single thing that can
 * cause it — RLS makes tenant isolation a database-level impossibility right
 * up until an admin client appears in a request path.
 *
 * `packages/db/scripts/check-admin-imports.ts` enforces the same rule with no
 * dependencies. Both are kept on purpose: this one gives an in-editor squiggle
 * at the moment the import is typed, that one still runs if ESLint is skipped,
 * misconfigured, or the config is edited. Two cheap checks on the highest
 * severity risk is not redundancy worth trimming.
 */
export default tseslint.config(
  {
    ignores: [
      "**/node_modules/**",
      "**/.next/**",
      "**/dist/**",
      "**/build/**",
      "package-lock.json",
      // Generated by Next on every build and overwritten if edited.
      "**/next-env.d.ts",
    ],
  },

  js.configs.recommended,
  ...tseslint.configs.recommended,

  {
    rules: {
      // Unused args are fine when prefixed with _, which is the conventional
      // way to say "this exists to satisfy a signature".
      "@typescript-eslint/no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_" },
      ],
      // `any` is a real escape hatch at integration boundaries; warn so it
      // shows up in review rather than blocking a legitimate use.
      "@typescript-eslint/no-explicit-any": "warn",
    },
  },

  {
    name: "huntloop/tenant-boundary",
    files: ["apps/**/*.{ts,tsx,js,jsx,mjs}"],
    rules: {
      "no-restricted-imports": [
        "error",
        {
          paths: [
            {
              name: "@huntloop/db/admin",
              message:
                "The service-role client bypasses Row Level Security, which is " +
                "the tenant boundary (plan D2). Use createTenantClient() from " +
                "@huntloop/db instead. If RLS is blocking a legitimate read, " +
                "the policy is the bug — fix the policy, not the client.",
            },
          ],
          patterns: [
            {
              group: ["**/db/src/admin", "**/db/src/admin.*"],
              message:
                "Reaching past the package entry point to the service-role " +
                "client. See @huntloop/db/admin — and don't.",
            },
          ],
        },
      ],
    },
  },

  {
    // Scripts are operational tooling: they run in Node, outside the app, and
    // legitimately talk to the console.
    files: ["packages/db/scripts/**/*.ts"],
    rules: { "no-console": "off" },
  },
);
