import { z } from "zod";
import { CLAIM_KINDS, CONFIDENCES, PRIORITIES } from "@huntloop/ai";

/**
 * Schemas for everything that crosses a Server Action boundary.
 *
 * Server Actions are public POST endpoints. Next generates an id for each one
 * and exposes it to the browser, which means anyone can call them with
 * anything — and TypeScript is erased at runtime, so the parameter types on
 * `analyzeUrlAction(org: string, url: string)` are documentation, not a check.
 *
 * The existing code reasons about this correctly at each call site: a tampered
 * ICP produces recommendations traceable to that ICP and nothing more, so
 * there is nothing to escalate with. That argument is sound and it is also
 * re-derived by hand every time someone adds an action. This file makes it
 * structural instead — the shape is checked once, at the edge, and the reasoning
 * downstream gets to assume it.
 *
 * Two rules for what goes in here:
 *
 *   1. Validate *shape and bounds*, not business meaning. Whether a URL is a
 *      real company is `normalizeUrl`'s job and then the model's; whether the
 *      caller may act on this org is `resolveRecorder`'s. This layer only
 *      guarantees that what arrives is the kind of thing the code below expects.
 *   2. Bound every string and array. An unbounded field on a public endpoint is
 *      a way to make us pay to tokenize a megabyte of someone else's text.
 */

/**
 * Enum members are derived from the AI package rather than retyped.
 *
 * A literal union copied by hand here would drift the first time a priority or
 * a claim kind is added, and it would drift *silently* — the schema would keep
 * validating and start rejecting the new member as invalid input.
 */
const priority = z.enum(PRIORITIES);
const claimKind = z.enum(CLAIM_KINDS);
const confidence = z.enum(CONFIDENCES);

/** Org slugs are generated by `slugify`, which caps at 48 and emits [a-z0-9-]. */
export const orgSlugSchema = z
  .string()
  .min(1)
  .max(48)
  .regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/, "Not a valid organisation slug.");

/**
 * An organisation name, as typed into the sign-up form.
 *
 * `z.string()` rather than `String(value)`: a `FormData` entry is
 * `string | File`, and coercing a File yields the literal `"[object File]"` —
 * which passes a non-empty check, slugifies to `objectfile`, and creates an
 * organisation. Rejecting the wrong type is the whole job here.
 *
 * 120 is well past any real company name and stops the field being a way to
 * put a megabyte into a `text` column.
 */
export const orgNameSchema = z.string().trim().min(1).max(120);

/**
 * A sign-in email address.
 *
 * `z.email()` for shape, and a length cap because the field is on an
 * unauthenticated endpoint. 254 is the RFC 5321 maximum for a whole address,
 * so anything longer is not an address that could ever be delivered to.
 *
 * Lowercased, because Supabase treats addresses case-insensitively and two
 * casings of the same mailbox arriving as two accounts is a support ticket
 * nobody enjoys.
 */
export const emailSchema = z.string().trim().toLowerCase().max(254).pipe(z.email());

/** Which form was submitted. Decides `shouldCreateUser`, so it is not free-form. */
export const authModeSchema = z.enum(["login", "signup"]);

/**
 * What a user may paste into "analyze a URL".
 *
 * Deliberately loose: people type `acme.co` without a scheme, and rejecting
 * that here would break the thing `normalizeUrl` exists to handle. The cap is
 * the point — 2048 is the conventional practical URL limit.
 */
export const urlInputSchema = z.string().trim().min(1).max(2048);

const shortText = z.string().max(400);
const stringList = z.array(shortText).max(50);

export const icpSchema = z.object({
  sells: z.string().max(2000),
  segments: stringList,
  sizes: stringList,
  regions: stringList,
  triggers: stringList,
  exclusions: stringList,
});

/**
 * The evidence the analyze screen hands back when asking "why now".
 *
 * This one genuinely originates in the browser — it is the evidence just
 * rendered on screen — and `explain_why_now` already constrains its reasoning
 * to the claims it is given, so a rewritten list produces a why-now traceable
 * to that list and nothing more. The bounds below are therefore about cost,
 * not trust: without them a caller could hand us 500 claims of 50 kB each and
 * we would pay to have Opus read all of it.
 */
export const whyNowRequestSchema = z.object({
  companyName: shortText,
  canonicalDomain: z.string().max(253),
  priority,
  evidence: z
    .array(
      z.object({
        claim: z.string().max(2000),
        kind: claimKind,
        confidence: confidence.nullable(),
        sourceUrl: z.string().max(2048).nullable(),
        excerpt: z.string().max(2000).nullable(),
      }),
    )
    .max(40),
});

/**
 * Parses, or returns a message fit to show a user.
 *
 * Returning rather than throwing, because every action already has a failure
 * branch that renders — throwing would route a bad request to the error
 * boundary, which is where *unexpected* failures belong. Malformed input to a
 * public endpoint is entirely expected.
 *
 * The message never echoes the received value. On a public endpoint that is
 * both a reflection risk and a way to confirm what the parser accepts.
 */
export function parseInput<T>(
  schema: z.ZodType<T>,
  value: unknown,
  what: string,
): { ok: true; value: T } | { ok: false; error: string } {
  const result = schema.safeParse(value);
  if (result.success) return { ok: true, value: result.data };
  return { ok: false, error: `That ${what} isn't something we can work with.` };
}

/* ── Module schemas ─────────────────────────────────────────────────────────
 *
 * Everything below backs a Server Action behind authentication. The two rules
 * at the top of this file still apply, and the second one — bound every string
 * and array — is the one that matters here: these endpoints write to `text`
 * columns, and an unbounded field is a way to put a megabyte in one.
 *
 * `uuidSchema` is used wherever an id crosses the boundary. It is not an
 * authorization check — RLS is — but it turns a tampered id into a sentence
 * instead of Postgres error `22P02`, which is a 500 where a message belongs.
 */

export const uuidSchema = z.string().uuid("That reference isn't valid.");

const name = z.string().trim().min(1, "This can't be empty.").max(160);
const longText = z.string().trim().max(4000);
const optionalUrl = z.string().trim().max(2048).optional().or(z.literal(""));

export const productSchema = z.object({
  id: uuidSchema.optional(),
  name,
  website: optionalUrl,
  description: longText,
  valueProps: stringList,
  proofPoints: stringList,
});

export const icpFormSchema = z.object({
  id: uuidSchema.optional(),
  name,
  productId: uuidSchema.optional().or(z.literal("")),
  segments: stringList,
  sizes: stringList,
  regions: stringList,
  triggers: stringList,
  exclusions: stringList,
  isActive: z.boolean().optional(),
});

export const personaSchema = z.object({
  id: uuidSchema.optional(),
  icpId: uuidSchema,
  name,
  titlePatterns: stringList,
  seniority: stringList,
  painPoints: stringList,
});

export const sourceSchema = z.object({
  id: uuidSchema.optional(),
  name,
  kind: z.enum([
    "news", "blog", "jobs", "social", "github", "funding",
    "regulatory", "community", "podcast", "custom",
  ]),
  url: optionalUrl,
  icpId: uuidSchema.optional().or(z.literal("")),
});

export const companySchema = z.object({
  id: uuidSchema.optional(),
  name,
  /* A hostname, not a URL. 253 is the DNS maximum for a fully qualified name,
     so anything longer is not a domain that could ever resolve. */
  domain: z.string().trim().min(1, "A domain is required.").max(253),
  industry: z.string().trim().max(120).optional().or(z.literal("")),
  website: optionalUrl,
  country: z.string().trim().max(80).optional().or(z.literal("")),
  region: z.string().trim().max(80).optional().or(z.literal("")),
  employeeCount: z.number().int().min(0).max(10_000_000).nullable().optional(),
  businessModel: z.string().trim().max(120).optional().or(z.literal("")),
  description: longText.optional(),
});

/**
 * A pasted CSV.
 *
 * 2 MB is roughly 20,000 company rows — past what anyone pastes into a
 * textarea and far short of what would hurt to parse. The row cap in the
 * importer is the real bound; this one stops the request body being the
 * attack.
 */
export const csvSchema = z.string().max(2_000_000);

export const campaignSchema = z.object({
  id: uuidSchema.optional(),
  name,
  icpId: uuidSchema.optional().or(z.literal("")),
  productId: uuidSchema.optional().or(z.literal("")),
  /* §46's autonomy ladder. Bounded here as well as by the check constraint,
     so an out-of-range value is a sentence rather than a Postgres error. */
  autonomyLevel: z.number().int().min(0).max(5),
  status: z.enum(["draft", "active", "paused", "archived"]),
});

export const sequenceStepSchema = z.object({
  id: uuidSchema.optional(),
  sequenceId: uuidSchema,
  position: z.number().int().min(0).max(50),
  kind: z.enum(["email", "wait", "condition"]),
  delayHours: z.number().int().min(0).max(24 * 365),
  subject: z.string().trim().max(400).optional(),
  body: z.string().trim().max(20_000).optional(),
});

export const memorySchema = z.object({
  id: uuidSchema.optional(),
  scope: z.enum(["organization", "team", "user", "account", "opportunity"]),
  scopeId: uuidSchema.nullable().optional(),
  key: z.string().trim().max(160).optional().or(z.literal("")),
  content: z.string().trim().min(1, "A memory can't be empty.").max(4000),
  confidence: confidence.nullable().optional(),
});

/**
 * How often a source may be re-read, in minutes.
 *
 * A closed set rather than a range, because it is rendered as a dropdown and
 * every value in it is a sentence a user can reason about. The floor of 5 is
 * also a CHECK in 0008 — this is somebody else's server, and a source polled
 * every thirty seconds is a source whose operator blocks us.
 */
export const scanIntervalSchema = z.union([
  z.literal(15),
  z.literal(60),
  z.literal(360),
  z.literal(1440),
  z.literal(10080),
]);

export const memberRoleSchema = z.enum(["owner", "admin", "member", "viewer"]);

/**
 * An invitation.
 *
 * `owner` is deliberately not offerable here. Promoting somebody to owner is
 * a deliberate act performed on a member who has already arrived and been
 * recognised — doing it by typing an address into a box means a typo grants
 * the highest privilege in the organisation to whoever happens to control
 * that mailbox.
 */
export const inviteSchema = z.object({
  email: emailSchema,
  role: z.enum(["admin", "member", "viewer"]),
});

export const orgSettingsSchema = z.object({
  name: orgNameSchema,
});

export const opportunityStatusSchema = z.enum([
  "discovered", "researching", "qualified", "assigned", "contacted",
  "replied", "meeting", "proposal", "won", "lost", "archived",
]);

export const threadStatusSchema = z.enum(["open", "snoozed", "closed"]);

/**
 * Parses, and reports *which field* failed.
 *
 * `parseInput` above returns one sentence, which is right for a single scalar
 * — there is only one thing it could be about. It is wrong for a nine-field
 * form, where "that isn't something we can work with" makes the user re-read
 * every field to find the one that is wrong.
 *
 * The per-field messages come from the schema, so they are written once beside
 * the constraint rather than duplicated in each form.
 */
export function parseForm<T>(
  schema: z.ZodType<T>,
  value: unknown,
): { ok: true; value: T } | { ok: false; error: string; fieldErrors: Record<string, string> } {
  const result = schema.safeParse(value);
  if (result.success) return { ok: true, value: result.data };

  const fieldErrors: Record<string, string> = {};
  for (const issue of result.error.issues) {
    const key = issue.path.map(String).join(".");
    if (key && !fieldErrors[key]) fieldErrors[key] = issue.message;
  }

  return {
    ok: false,
    error: "Some of what you entered can't be saved. See the fields marked below.",
    fieldErrors,
  };
}

/**
 * The body of a reply a person typed.
 *
 * Bounded at the same 4 000 characters the schema's `body_text` is comfortable
 * with, and trimmed rather than rejected for whitespace — a reply pasted from
 * another client arrives with a trailing newline, and refusing that would be
 * refusing the commonest way of writing one.
 *
 * The lower bound is one character rather than some minimum sentence length.
 * "Yes." is a complete reply, and a product that argued with it would be
 * wrong about how sales conversations end.
 */
export const replyBodySchema = z
  .string()
  .trim()
  .min(1, "A reply needs something in it.")
  .max(4000, "That reply is longer than an email should be. Trim it to 4 000 characters.");
