import { z } from "zod";
import { CLAIM_KINDS, CONFIDENCES, PRIORITIES } from "@huntloop/ai";

/**
 * Schemas for everything that crosses a Server Action boundary.
 *
 * Server Actions are public POST endpoints. Next generates an id for each one
 * and exposes it to the browser, which means anyone can call them with
 * anything — and TypeScript is erased at runtime, so the parameter types on
 * `analyzeUrlAction(org: string, url: string)` are documentation, not a check.
 *
 * The existing code reasons about this correctly at each call site: a tampered
 * ICP produces recommendations traceable to that ICP and nothing more, so
 * there is nothing to escalate with. That argument is sound and it is also
 * re-derived by hand every time someone adds an action. This file makes it
 * structural instead — the shape is checked once, at the edge, and the reasoning
 * downstream gets to assume it.
 *
 * Two rules for what goes in here:
 *
 *   1. Validate *shape and bounds*, not business meaning. Whether a URL is a
 *      real company is `normalizeUrl`'s job and then the model's; whether the
 *      caller may act on this org is `resolveRecorder`'s. This layer only
 *      guarantees that what arrives is the kind of thing the code below expects.
 *   2. Bound every string and array. An unbounded field on a public endpoint is
 *      a way to make us pay to tokenize a megabyte of someone else's text.
 */

/**
 * Enum members are derived from the AI package rather than retyped.
 *
 * A literal union copied by hand here would drift the first time a priority or
 * a claim kind is added, and it would drift *silently* — the schema would keep
 * validating and start rejecting the new member as invalid input.
 */
const priority = z.enum(PRIORITIES);
const claimKind = z.enum(CLAIM_KINDS);
const confidence = z.enum(CONFIDENCES);

/** Org slugs are generated by `slugify`, which caps at 48 and emits [a-z0-9-]. */
export const orgSlugSchema = z
  .string()
  .min(1)
  .max(48)
  .regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/, "Not a valid organisation slug.");

/**
 * An organisation name, as typed into the sign-up form.
 *
 * `z.string()` rather than `String(value)`: a `FormData` entry is
 * `string | File`, and coercing a File yields the literal `"[object File]"` —
 * which passes a non-empty check, slugifies to `objectfile`, and creates an
 * organisation. Rejecting the wrong type is the whole job here.
 *
 * 120 is well past any real company name and stops the field being a way to
 * put a megabyte into a `text` column.
 */
export const orgNameSchema = z.string().trim().min(1).max(120);

/**
 * What a user may paste into "analyze a URL".
 *
 * Deliberately loose: people type `acme.co` without a scheme, and rejecting
 * that here would break the thing `normalizeUrl` exists to handle. The cap is
 * the point — 2048 is the conventional practical URL limit.
 */
export const urlInputSchema = z.string().trim().min(1).max(2048);

const shortText = z.string().max(400);
const stringList = z.array(shortText).max(50);

export const icpSchema = z.object({
  sells: z.string().max(2000),
  segments: stringList,
  sizes: stringList,
  regions: stringList,
  triggers: stringList,
  exclusions: stringList,
});

/**
 * The evidence the analyze screen hands back when asking "why now".
 *
 * This one genuinely originates in the browser — it is the evidence just
 * rendered on screen — and `explain_why_now` already constrains its reasoning
 * to the claims it is given, so a rewritten list produces a why-now traceable
 * to that list and nothing more. The bounds below are therefore about cost,
 * not trust: without them a caller could hand us 500 claims of 50 kB each and
 * we would pay to have Opus read all of it.
 */
export const whyNowRequestSchema = z.object({
  companyName: shortText,
  canonicalDomain: z.string().max(253),
  priority,
  evidence: z
    .array(
      z.object({
        claim: z.string().max(2000),
        kind: claimKind,
        confidence: confidence.nullable(),
        sourceUrl: z.string().max(2048).nullable(),
        excerpt: z.string().max(2000).nullable(),
      }),
    )
    .max(40),
});

/**
 * Parses, or returns a message fit to show a user.
 *
 * Returning rather than throwing, because every action already has a failure
 * branch that renders — throwing would route a bad request to the error
 * boundary, which is where *unexpected* failures belong. Malformed input to a
 * public endpoint is entirely expected.
 *
 * The message never echoes the received value. On a public endpoint that is
 * both a reflection risk and a way to confirm what the parser accepts.
 */
export function parseInput<T>(
  schema: z.ZodType<T>,
  value: unknown,
  what: string,
): { ok: true; value: T } | { ok: false; error: string } {
  const result = schema.safeParse(value);
  if (result.success) return { ok: true, value: result.data };
  return { ok: false, error: `That ${what} isn't something we can work with.` };
}
