// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/[org]/analytics" | "/[org]/analyze" | "/[org]/companies" | "/[org]/dashboard" | "/[org]/imports" | "/[org]/inbox" | "/[org]/intelligence" | "/[org]/learn" | "/[org]/memory" | "/[org]/opportunities" | "/[org]/opportunities/[id]" | "/[org]/ops" | "/[org]/outreach" | "/[org]/pipeline" | "/[org]/settings" | "/[org]/settings/icp" | "/[org]/settings/integrations" | "/[org]/settings/privacy" | "/[org]/settings/product" | "/[org]/settings/scoring" | "/[org]/sources" | "/[org]/team" | "/[org]/team/assignments" | "/acceptable-use" | "/compare/[approach]" | "/discover" | "/for/[useCase]" | "/invite/[token]" | "/kitchen-sink" | "/login" | "/orgs" | "/privacy" | "/signup" | "/terms" | "/unsubscribe/[token]" | "/welcome" | "/welcome/building" | "/welcome/company" | "/welcome/goals" | "/welcome/icp" | "/welcome/review" | "/welcome/sources"
type AppRouteHandlerRoutes = "/api/csp-report" | "/api/health" | "/api/inngest" | "/api/jobs/tick" | "/api/mailboxes/[provider]/callback" | "/api/mailboxes/[provider]/start" | "/api/unsubscribe/[token]" | "/auth/callback" | "/auth/signout"
type PageRoutes = never
type LayoutRoutes = "/" | "/[org]" | "/[org]/settings" | "/welcome"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/[org]": { "org": string; }
  "/[org]/analytics": { "org": string; }
  "/[org]/analyze": { "org": string; }
  "/[org]/companies": { "org": string; }
  "/[org]/dashboard": { "org": string; }
  "/[org]/imports": { "org": string; }
  "/[org]/inbox": { "org": string; }
  "/[org]/intelligence": { "org": string; }
  "/[org]/learn": { "org": string; }
  "/[org]/memory": { "org": string; }
  "/[org]/opportunities": { "org": string; }
  "/[org]/opportunities/[id]": { "org": string; "id": string; }
  "/[org]/ops": { "org": string; }
  "/[org]/outreach": { "org": string; }
  "/[org]/pipeline": { "org": string; }
  "/[org]/settings": { "org": string; }
  "/[org]/settings/icp": { "org": string; }
  "/[org]/settings/integrations": { "org": string; }
  "/[org]/settings/privacy": { "org": string; }
  "/[org]/settings/product": { "org": string; }
  "/[org]/settings/scoring": { "org": string; }
  "/[org]/sources": { "org": string; }
  "/[org]/team": { "org": string; }
  "/[org]/team/assignments": { "org": string; }
  "/acceptable-use": {}
  "/api/csp-report": {}
  "/api/health": {}
  "/api/inngest": {}
  "/api/jobs/tick": {}
  "/api/mailboxes/[provider]/callback": { "provider": string; }
  "/api/mailboxes/[provider]/start": { "provider": string; }
  "/api/unsubscribe/[token]": { "token": string; }
  "/auth/callback": {}
  "/auth/signout": {}
  "/compare/[approach]": { "approach": string; }
  "/discover": {}
  "/for/[useCase]": { "useCase": string; }
  "/invite/[token]": { "token": string; }
  "/kitchen-sink": {}
  "/login": {}
  "/orgs": {}
  "/privacy": {}
  "/signup": {}
  "/terms": {}
  "/unsubscribe/[token]": { "token": string; }
  "/welcome": {}
  "/welcome/building": {}
  "/welcome/company": {}
  "/welcome/goals": {}
  "/welcome/icp": {}
  "/welcome/review": {}
  "/welcome/sources": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/[org]": never
  "/[org]/settings": never
  "/welcome": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
