// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../app/(app)/[org]/analytics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[org]/analytics">> = Specific
  const handler = {} as typeof import("../../../app/(app)/[org]/analytics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/[org]/analyze/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[org]/analyze">> = Specific
  const handler = {} as typeof import("../../../app/(app)/[org]/analyze/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/[org]/companies/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[org]/companies">> = Specific
  const handler = {} as typeof import("../../../app/(app)/[org]/companies/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/[org]/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[org]/dashboard">> = Specific
  const handler = {} as typeof import("../../../app/(app)/[org]/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/[org]/imports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[org]/imports">> = Specific
  const handler = {} as typeof import("../../../app/(app)/[org]/imports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/[org]/inbox/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[org]/inbox">> = Specific
  const handler = {} as typeof import("../../../app/(app)/[org]/inbox/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/[org]/intelligence/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[org]/intelligence">> = Specific
  const handler = {} as typeof import("../../../app/(app)/[org]/intelligence/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/[org]/learn/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[org]/learn">> = Specific
  const handler = {} as typeof import("../../../app/(app)/[org]/learn/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/[org]/memory/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[org]/memory">> = Specific
  const handler = {} as typeof import("../../../app/(app)/[org]/memory/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/[org]/opportunities/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[org]/opportunities/[id]">> = Specific
  const handler = {} as typeof import("../../../app/(app)/[org]/opportunities/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/[org]/opportunities/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[org]/opportunities">> = Specific
  const handler = {} as typeof import("../../../app/(app)/[org]/opportunities/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/[org]/ops/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[org]/ops">> = Specific
  const handler = {} as typeof import("../../../app/(app)/[org]/ops/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/[org]/outreach/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[org]/outreach">> = Specific
  const handler = {} as typeof import("../../../app/(app)/[org]/outreach/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/[org]/pipeline/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[org]/pipeline">> = Specific
  const handler = {} as typeof import("../../../app/(app)/[org]/pipeline/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/[org]/settings/icp/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[org]/settings/icp">> = Specific
  const handler = {} as typeof import("../../../app/(app)/[org]/settings/icp/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/[org]/settings/integrations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[org]/settings/integrations">> = Specific
  const handler = {} as typeof import("../../../app/(app)/[org]/settings/integrations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/[org]/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[org]/settings">> = Specific
  const handler = {} as typeof import("../../../app/(app)/[org]/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/[org]/settings/privacy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[org]/settings/privacy">> = Specific
  const handler = {} as typeof import("../../../app/(app)/[org]/settings/privacy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/[org]/settings/product/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[org]/settings/product">> = Specific
  const handler = {} as typeof import("../../../app/(app)/[org]/settings/product/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/[org]/settings/scoring/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[org]/settings/scoring">> = Specific
  const handler = {} as typeof import("../../../app/(app)/[org]/settings/scoring/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/[org]/sources/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[org]/sources">> = Specific
  const handler = {} as typeof import("../../../app/(app)/[org]/sources/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/[org]/team/assignments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[org]/team/assignments">> = Specific
  const handler = {} as typeof import("../../../app/(app)/[org]/team/assignments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/[org]/team/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[org]/team">> = Specific
  const handler = {} as typeof import("../../../app/(app)/[org]/team/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/orgs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/orgs">> = Specific
  const handler = {} as typeof import("../../../app/(app)/orgs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(auth)/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../../app/(auth)/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(auth)/signup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/signup">> = Specific
  const handler = {} as typeof import("../../../app/(auth)/signup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(marketing)/acceptable-use/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/acceptable-use">> = Specific
  const handler = {} as typeof import("../../../app/(marketing)/acceptable-use/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(marketing)/compare/[approach]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/compare/[approach]">> = Specific
  const handler = {} as typeof import("../../../app/(marketing)/compare/[approach]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(marketing)/discover/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/discover">> = Specific
  const handler = {} as typeof import("../../../app/(marketing)/discover/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(marketing)/for/[useCase]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/for/[useCase]">> = Specific
  const handler = {} as typeof import("../../../app/(marketing)/for/[useCase]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(marketing)/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/(marketing)/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(marketing)/privacy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/privacy">> = Specific
  const handler = {} as typeof import("../../../app/(marketing)/privacy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(marketing)/terms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/terms">> = Specific
  const handler = {} as typeof import("../../../app/(marketing)/terms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(onboarding)/welcome/building/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/welcome/building">> = Specific
  const handler = {} as typeof import("../../../app/(onboarding)/welcome/building/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(onboarding)/welcome/company/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/welcome/company">> = Specific
  const handler = {} as typeof import("../../../app/(onboarding)/welcome/company/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(onboarding)/welcome/goals/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/welcome/goals">> = Specific
  const handler = {} as typeof import("../../../app/(onboarding)/welcome/goals/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(onboarding)/welcome/icp/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/welcome/icp">> = Specific
  const handler = {} as typeof import("../../../app/(onboarding)/welcome/icp/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(onboarding)/welcome/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/welcome">> = Specific
  const handler = {} as typeof import("../../../app/(onboarding)/welcome/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(onboarding)/welcome/review/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/welcome/review">> = Specific
  const handler = {} as typeof import("../../../app/(onboarding)/welcome/review/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(onboarding)/welcome/sources/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/welcome/sources">> = Specific
  const handler = {} as typeof import("../../../app/(onboarding)/welcome/sources/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/invite/[token]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/invite/[token]">> = Specific
  const handler = {} as typeof import("../../../app/invite/[token]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/kitchen-sink/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/kitchen-sink">> = Specific
  const handler = {} as typeof import("../../../app/kitchen-sink/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/unsubscribe/[token]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/unsubscribe/[token]">> = Specific
  const handler = {} as typeof import("../../../app/unsubscribe/[token]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/csp-report/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/csp-report">> = Specific
  const handler = {} as typeof import("../../../app/api/csp-report/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/health/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/health">> = Specific
  const handler = {} as typeof import("../../../app/api/health/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/inngest/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/inngest">> = Specific
  const handler = {} as typeof import("../../../app/api/inngest/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/jobs/tick/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/jobs/tick">> = Specific
  const handler = {} as typeof import("../../../app/api/jobs/tick/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/mailboxes/[provider]/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mailboxes/[provider]/callback">> = Specific
  const handler = {} as typeof import("../../../app/api/mailboxes/[provider]/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/mailboxes/[provider]/start/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mailboxes/[provider]/start">> = Specific
  const handler = {} as typeof import("../../../app/api/mailboxes/[provider]/start/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/unsubscribe/[token]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/unsubscribe/[token]">> = Specific
  const handler = {} as typeof import("../../../app/api/unsubscribe/[token]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/auth/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/auth/callback">> = Specific
  const handler = {} as typeof import("../../../app/auth/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/auth/signout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/auth/signout">> = Specific
  const handler = {} as typeof import("../../../app/auth/signout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../app/(app)/[org]/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/[org]">> = Specific
  const handler = {} as typeof import("../../../app/(app)/[org]/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/[org]/settings/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/[org]/settings">> = Specific
  const handler = {} as typeof import("../../../app/(app)/[org]/settings/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(auth)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/(auth)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(onboarding)/welcome/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/welcome">> = Specific
  const handler = {} as typeof import("../../../app/(onboarding)/welcome/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
